-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-04-26 21:53:38 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE NL_ARL_Emp CASCADE CONSTRAINTS ;

DROP TABLE NL_Document CASCADE CONSTRAINTS ;

DROP TABLE NL_Member CASCADE CONSTRAINTS ;

DROP TABLE NL_division CASCADE CONSTRAINTS ;

DROP TABLE NL_lab CASCADE CONSTRAINTS ;

DROP TABLE NL_mem_NL CASCADE CONSTRAINTS ;

CREATE TABLE NL_ARL_Emp
(
 user_id             INTEGER NOT NULL ,
 name                VARCHAR2 (4000) ,
 status              VARCHAR2 (255) ,
 status_eff_date     DATE ,
 lab_code            INTEGER ,
 division_code       INTEGER ,
 NL_Member_member_id INTEGER
 ) ;
CREATE UNIQUE INDEX NL_ARL_Emp__IDX ON NL_ARL_Emp
(
 NL_Member_member_id ASC
 )
;
ALTER TABLE NL_ARL_Emp ADD CONSTRAINT NL_ARL_Emp_PK PRIMARY KEY ( user_id ) ;

CREATE TABLE NL_Document
(
 document_id   INTEGER NOT NULL ,
 filename      VARCHAR2 (4000 BYTE) ,
 file_mimetype VARCHAR2 (512) ,
 file_charset  VARCHAR2 (512) ,
 file_data BLOB ,
 file_comments       VARCHAR2 (4000) ,
 tags                VARCHAR2 (4000) ,
 NL_Member_member_id INTEGER
 ) ;
ALTER TABLE NL_Document ADD CONSTRAINT NL_Document_PK PRIMARY KEY ( document_id ) ;

CREATE TABLE NL_Member
(
 member_id          INTEGER NOT NULL ,
 type               VARCHAR2 (255) ,
 name               VARCHAR2 (4000) ,
 status_eff_date    DATE ,
 lab_code           INTEGER ,
 division_code      INTEGER ,
 status             VARCHAR2 (255) ,
 NL_ARL_Emp_user_id INTEGER ,
 description        VARCHAR2 (4000) ,
 ownership_div_code INTEGER ,
 external_view_name VARCHAR2 (4000)
 ) ;
CREATE UNIQUE INDEX NL_Member__IDX ON NL_Member
(
 NL_ARL_Emp_user_id ASC
 )
;
ALTER TABLE NL_Member ADD CONSTRAINT NL_Member_PK PRIMARY KEY ( member_id ) ;

CREATE TABLE NL_division
(
 division_id   INTEGER NOT NULL ,
 name          VARCHAR2 (4000) ,
 NL_lab_lab_id INTEGER
 ) ;
CREATE UNIQUE INDEX NL_division__IDX ON NL_division
(
 NL_lab_lab_id ASC
 )
;
ALTER TABLE NL_division ADD CONSTRAINT NL_division_PK PRIMARY KEY ( division_id ) ;

CREATE TABLE NL_lab
(
 lab_id                  INTEGER NOT NULL ,
 name                    VARCHAR2 (4000) ,
 NL_division_division_id INTEGER
 ) ;
CREATE UNIQUE INDEX NL_lab__IDX ON NL_lab
(
 NL_division_division_id ASC
 )
;
ALTER TABLE NL_lab ADD CONSTRAINT NL_lab_PK PRIMARY KEY ( lab_id ) ;

CREATE TABLE NL_mem_NL
(
 NL_Member_member_id  INTEGER ,
 NL_Member_member_id1 INTEGER
 ) ;

ALTER TABLE NL_ARL_Emp ADD CONSTRAINT NL_ARL_Emp_NL_Member_FK FOREIGN KEY ( NL_Member_member_id ) REFERENCES NL_Member ( member_id ) ;

ALTER TABLE NL_Document ADD CONSTRAINT NL_Document_NL_Member_FK FOREIGN KEY ( NL_Member_member_id ) REFERENCES NL_Member ( member_id ) ;

ALTER TABLE NL_Member ADD CONSTRAINT NL_Member_NL_ARL_Emp_FK FOREIGN KEY ( NL_ARL_Emp_user_id ) REFERENCES NL_ARL_Emp ( user_id ) ;

ALTER TABLE NL_division ADD CONSTRAINT NL_division_NL_lab_FK FOREIGN KEY ( NL_lab_lab_id ) REFERENCES NL_lab ( lab_id ) ;

ALTER TABLE NL_lab ADD CONSTRAINT NL_lab_NL_division_FK FOREIGN KEY ( NL_division_division_id ) REFERENCES NL_division ( division_id ) ;

ALTER TABLE NL_mem_NL ADD CONSTRAINT NL_mem_NL_NL_Member_FK FOREIGN KEY ( NL_Member_member_id ) REFERENCES NL_Member ( member_id ) ;

ALTER TABLE NL_mem_NL ADD CONSTRAINT NL_mem_NL_NL_Member_FKv1 FOREIGN KEY ( NL_Member_member_id1 ) REFERENCES NL_Member ( member_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             6
-- CREATE INDEX                             4
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ERRORS                                   0
-- WARNINGS                                 0
